
<h3>Terms & Conditions:</h3>
<p>The Service is only available to individuals aged 18 years or over and who are resident in and accessing the Service from Australia. By using the Service you represent and warrant to us that the details that you have provided (including the details about the Recipient) are true and correct.
In order to use our Service, we need you to provide us with information to satisfactorily establish</p> <p>your identity for the purpose of complying with antimoney laundering and counter terrorism financing legislation (AML/CTF) in Australia and elsewhere. You will need to provide us with certain mandatory information before we can proceed with your transaction. For example, you will need to provide us with your name and residential address.</p>
<p>The Service must not be used for any illegal or improper purposes. If you are using the Service to make a payment in consideration for goods or services (obtained online or otherwise), you agree to comply with all applicable laws and regulations in each relevant jurisdiction in relation to that transaction and agree to not involve PT Money Transfer as a party to such a transaction. As the Service is a remittance service only, PT Money Transfer does not provide any purchase guarantee or protection for goods and services paid for via the Service. You are cautioned against sending money to any person you do not know.</p>
<p>The User must provide to PT Money Transfer all the information as required under the relevant screen for us to process the transfer, in particular, the recipient’s 10 digit bank account number. The Sender is responsible for providing proper, correct, accurate and complete details of such requested information. PT Money Transfer is not responsible to verify or authenticate such information. By requesting and authorising a transfer of funds, you confirm that all the details contained in the request are correct in all respects. You are responsible for ensuring that the Recipient Bank Account Number that you provide is correct. If the Recipient Account number you provide is incorrect or if erroneous information is provided, the funds could be transferred to an incorrect recipient account. In the event that erroneous information is provided by the sender, PT Money Transfer is not responsible for reversing the erroneous transaction or guaranteeing recovery of the funds transferred as a result of that erroneous transaction</p>
<p>We may, at any time, decline to process your transfer of funds for any reason, including where insufficient or incorrect information has been provided or an exchange rate has been quoted in error. We may also, at any time and at our sole discretion, decline to process your transfer of funds if it is in our opinion that the transfer of funds will contravene any of the sanctions prescribed by the Reserve Bank of Australia (RBA), the Australian Department of Foreign Affairs and Trade (DFAT) or would otherwise be prohibited by law. PT Money transfer reserves the right to recover or reverse the funds transferred into the recipient’s account in an event that there are mistakes within the transaction. The recipient MUST willingly return ALL of the funds transferred into their account to PT Money Transfer. The Sender agrees to return incorrect transferred funds to PT Money Transfer in an event that such funds are not recoverable from the Sender’s recipient.</p>
<p>The exchange rates we quote are specific to each transaction only. Exchange rates constantly fluctuate and the rate you get for one transaction may be different from another transaction. We will use the exchange rate (asset by us) that we quote to you at the time we receive your request.</p>/
<p>Please note that the overseas bank may charge the recipient for processing fees before paying out to beneficiary account. PT Money Transfer will not be responsible for extra fees incurred or charges by recipient’s bank in an event that there are more charges than the estimated fee deducted by us within the transaction.</p>
<p>In the event that the transfer of funds is unsuccessful, we will notify you by phone via the phone number you have provided to us at the earliest possible time. Unless prohibited by law, we will return the relevant funds to you converted back to AUD at a rate determined by us as applicable on the day we process the conversion and minus any transaction processing fees incurred on the relevant transaction.</p>
<p>Correction & Amendment fee of AUD$10.00 per instruction applies if recipient’s detail need to be corrected in order for PT Money Transfer to finalise and complete the transaction. To avoid this fee, please check the transfer instruction carefully, especially spellings of beneficiary/account name in English (must match the destination banks database) and account number</p>
<p>By making a payment using the Service from PT Money Transfer, you confirm that you have read and understood these Terms and Conditions and agree to be bound by them and to comply with all applicable laws and regulations.PT Money transfer reserves the right to refuse this Service to any person found to be acting outside these Terms and Conditions.</p>
<p>Pt money transfer has the right to recover funds transferred from the sender and receiver in an event of errors in the transactions. All funds must be return upon request or we may seek legal actions against both sender and receiver.</p>